


services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4z5636spxr1p8wxkb186akyr84e4e7o78
    networks:
      web_tech_network:
            ipv4_address: 10.0.6.2

  app:
    image: containerninjadev/webprogproject:latest  
    container_name: web-app
    ports:
      - "80:8080"
    networks:
      web_tech_network:
        ipv4_address: 10.0.6.3
    depends_on:
      - db

networks:
  web_tech_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.6.0/24


# docker-compose up