// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChainTag", b =>
                {
                    b.Property<int>("ChainId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("ChainId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ChainTag");
                });

            modelBuilder.Entity("Core.Common.Chain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<string>("PentestObj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepChainLastId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Chains");
                });

            modelBuilder.Entity("Core.Common.ChainStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("End")
                        .HasColumnType("date");

                    b.Property<int>("FatherChainId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Start")
                        .HasColumnType("date");

                    b.Property<int>("StepId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FatherChainId");

                    b.ToTable("ChainSteps");
                });

            modelBuilder.Entity("Core.Common.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InstrumentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstrumentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TagColor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            InstrumentName = "nmap",
                            InstrumentUrl = "https://nmap.org/",
                            TagColor = 0
                        },
                        new
                        {
                            Id = -2,
                            InstrumentName = "BurpSuite",
                            InstrumentUrl = "https://portswigger.net/burp",
                            TagColor = 1
                        },
                        new
                        {
                            Id = -3,
                            InstrumentName = "Metasploit",
                            InstrumentUrl = "https://github.com/rapid7/metasploit-framework",
                            TagColor = 2
                        },
                        new
                        {
                            Id = -4,
                            InstrumentName = "OWASP",
                            InstrumentUrl = "https://owasp.org/www-community/Vulnerability_Scanning_Tools",
                            TagColor = 3
                        },
                        new
                        {
                            Id = -5,
                            InstrumentName = "WPScan",
                            InstrumentUrl = "https://kali.tools/?p=156",
                            TagColor = 4
                        },
                        new
                        {
                            Id = -6,
                            InstrumentName = "sqlmap",
                            InstrumentUrl = "https://kali.tools/?p=816",
                            TagColor = 5
                        },
                        new
                        {
                            Id = -7,
                            InstrumentName = "wfuz",
                            InstrumentUrl = "https://github.com/xmendez/wfuzz",
                            TagColor = 6
                        });
                });

            modelBuilder.Entity("Core.Common.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HashPassword = "a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("ChainTag", b =>
                {
                    b.HasOne("Core.Common.Chain", null)
                        .WithMany()
                        .HasForeignKey("ChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Common.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Common.Chain", b =>
                {
                    b.HasOne("Core.Common.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Core.Common.ChainStep", b =>
                {
                    b.HasOne("Core.Common.Chain", "FatherChain")
                        .WithMany()
                        .HasForeignKey("FatherChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FatherChain");
                });
#pragma warning restore 612, 618
        }
    }
}
